namespace Assets.Scripts.Craiel.Essentials.Enums
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public static class EnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by EnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IList<BundleLoadFlags> BundleLoadFlagsValues = Enum.GetValues(typeof(BundleLoadFlags)).Cast<BundleLoadFlags>().ToList();

        public static readonly IList<DelayedLoadedObjectPhase> DelayedLoadedObjectPhaseValues = Enum.GetValues(typeof(DelayedLoadedObjectPhase)).Cast<DelayedLoadedObjectPhase>().ToList();

        public static readonly IList<InputAxisMode> InputAxisModeValues = Enum.GetValues(typeof(InputAxisMode)).Cast<InputAxisMode>().ToList();

        public static readonly IList<InputMappingState> InputMappingStateValues = Enum.GetValues(typeof(InputMappingState)).Cast<InputMappingState>().ToList();

        public static readonly IList<ResourceLoadFlags> ResourceLoadFlagsValues = Enum.GetValues(typeof(ResourceLoadFlags)).Cast<ResourceLoadFlags>().ToList();

        public static readonly IList<ResourceLoadMode> ResourceLoadModeValues = Enum.GetValues(typeof(ResourceLoadMode)).Cast<ResourceLoadMode>().ToList();

        public static readonly IList<SceneRootCategory> SceneRootCategoryValues = Enum.GetValues(typeof(SceneRootCategory)).Cast<SceneRootCategory>().ToList();

        public static readonly IList<SceneTransitionStep> SceneTransitionStepValues = Enum.GetValues(typeof(SceneTransitionStep)).Cast<SceneTransitionStep>().ToList();

    }
}
