namespace Craiel.UnityAudio.Runtime.Enums
{
    using System.Collections.Generic;
    using System.Linq;
    using UnityEssentials.Runtime;

    public static class AudioEnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by AudioEnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IList<AudioChannel> AudioChannelValues = EnumCache<AudioChannel>.Values.ToList();

        public static readonly IList<AudioFlags> AudioFlagsValues = EnumCache<AudioFlags>.Values.ToList();

        public static readonly IList<AudioPlayBehavior> AudioPlayBehaviorValues = EnumCache<AudioPlayBehavior>.Values.ToList();

        public static readonly IList<DynamicAudioSourceState> DynamicAudioSourceStateValues = EnumCache<DynamicAudioSourceState>.Values.ToList();

        public static readonly IList<AudioEvent> AudioEventValues = EnumCache<AudioEvent>.Values.ToList();

    }
}
